### ISSUE TITLE
tomlcpp does not build on NixOS (because of missing headers)

### ISSUE THREAD

**Issue by AndersonTorres** [cktan/tomlcpp#3]
Well, the text is self-explanatory.
I have tried to build it on Nixpkgs, however it failed with a huge message about certain classes and data structures not being found.

It was fixed with this patch that includes them:

https://github.com/NixOS/nixpkgs/pull/168648/files#diff-0b192c7b76309153e81c2a05cf367b56e7dd225d77484e387f2ed800f1ee5f06

**Comment by cktan** [comment]
pls submit the missing headers change only. we can't maintain the other nix specific files.

**Comment by AndersonTorres** [comment]
Okay then :)
